// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRedisClient creates a new instance of MockIRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRedisClient {
	mock := &MockIRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRedisClient is an autogenerated mock type for the IRedisClient type
type MockIRedisClient struct {
	mock.Mock
}

type MockIRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRedisClient) EXPECT() *MockIRedisClient_Expecter {
	return &MockIRedisClient_Expecter{mock: &_m.Mock}
}

// LPush provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) LPush(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for LPush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRedisClient_LPush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LPush'
type MockIRedisClient_LPush_Call struct {
	*mock.Call
}

// LPush is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockIRedisClient_Expecter) LPush(ctx interface{}, key interface{}, value interface{}) *MockIRedisClient_LPush_Call {
	return &MockIRedisClient_LPush_Call{Call: _e.mock.On("LPush", ctx, key, value)}
}

func (_c *MockIRedisClient_LPush_Call) Run(run func(ctx context.Context, key string, value string)) *MockIRedisClient_LPush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRedisClient_LPush_Call) Return(err error) *MockIRedisClient_LPush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRedisClient_LPush_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockIRedisClient_LPush_Call {
	_c.Call.Return(run)
	return _c
}

// ZAdd provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) ZAdd(ctx context.Context, key string, score float64, member string) error {
	ret := _mock.Called(ctx, key, score, member)

	if len(ret) == 0 {
		panic("no return value specified for ZAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, string) error); ok {
		r0 = returnFunc(ctx, key, score, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRedisClient_ZAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZAdd'
type MockIRedisClient_ZAdd_Call struct {
	*mock.Call
}

// ZAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - score float64
//   - member string
func (_e *MockIRedisClient_Expecter) ZAdd(ctx interface{}, key interface{}, score interface{}, member interface{}) *MockIRedisClient_ZAdd_Call {
	return &MockIRedisClient_ZAdd_Call{Call: _e.mock.On("ZAdd", ctx, key, score, member)}
}

func (_c *MockIRedisClient_ZAdd_Call) Run(run func(ctx context.Context, key string, score float64, member string)) *MockIRedisClient_ZAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRedisClient_ZAdd_Call) Return(err error) *MockIRedisClient_ZAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRedisClient_ZAdd_Call) RunAndReturn(run func(ctx context.Context, key string, score float64, member string) error) *MockIRedisClient_ZAdd_Call {
	_c.Call.Return(run)
	return _c
}
