services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9091" /data
    networks:
      - monitoring
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - minio
    networks:
      - monitoring
    # restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6397
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - ./configs:/app/configs
    command: ["air", "-c", "/app/.air.toml"]

  prometheus:
    image: prom/prometheus:v2.53.5
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    # restart: unless-stopped
    depends_on:
      - api
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    # restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
    - 'grafana-storage:/var/lib/grafana'
    networks:
      - monitoring
    environment:
      - GR_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-storage: 
  go-mod-cache:

networks:
  monitoring:
    driver: bridge