{
 "title": "Resources",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"api\"}",
     "legendFormat": "api"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "api" }
   ]
  },
  {
   "title": "CPU Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{}[1m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Routine",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(go_goroutines)", "legendFormat": "__auto" }
   ]
  }
 ]
}