services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:v2.53.5
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  prometheus-data: