// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRedisClient creates a new instance of MockIRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRedisClient {
	mock := &MockIRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRedisClient is an autogenerated mock type for the IRedisClient type
type MockIRedisClient struct {
	mock.Mock
}

type MockIRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRedisClient) EXPECT() *MockIRedisClient_Expecter {
	return &MockIRedisClient_Expecter{mock: &_m.Mock}
}

// BRPop provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) BRPop(ctx context.Context, timeout time.Duration, keys ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, timeout, keys)
	} else {
		tmpRet = _mock.Called(ctx, timeout)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BRPop")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, ...string) (string, error)); ok {
		return returnFunc(ctx, timeout, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, ...string) string); ok {
		r0 = returnFunc(ctx, timeout, keys...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, ...string) error); ok {
		r1 = returnFunc(ctx, timeout, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRedisClient_BRPop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BRPop'
type MockIRedisClient_BRPop_Call struct {
	*mock.Call
}

// BRPop is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
//   - keys ...string
func (_e *MockIRedisClient_Expecter) BRPop(ctx interface{}, timeout interface{}, keys ...interface{}) *MockIRedisClient_BRPop_Call {
	return &MockIRedisClient_BRPop_Call{Call: _e.mock.On("BRPop",
		append([]interface{}{ctx, timeout}, keys...)...)}
}

func (_c *MockIRedisClient_BRPop_Call) Run(run func(ctx context.Context, timeout time.Duration, keys ...string)) *MockIRedisClient_BRPop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockIRedisClient_BRPop_Call) Return(s string, err error) *MockIRedisClient_BRPop_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRedisClient_BRPop_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration, keys ...string) (string, error)) *MockIRedisClient_BRPop_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) Del(ctx context.Context, keys ...string) (int64, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (int64, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) int64); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRedisClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockIRedisClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockIRedisClient_Expecter) Del(ctx interface{}, keys ...interface{}) *MockIRedisClient_Del_Call {
	return &MockIRedisClient_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockIRedisClient_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockIRedisClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIRedisClient_Del_Call) Return(n int64, err error) *MockIRedisClient_Del_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIRedisClient_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) (int64, error)) *MockIRedisClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// LPush provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) LPush(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for LPush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRedisClient_LPush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LPush'
type MockIRedisClient_LPush_Call struct {
	*mock.Call
}

// LPush is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockIRedisClient_Expecter) LPush(ctx interface{}, key interface{}, value interface{}) *MockIRedisClient_LPush_Call {
	return &MockIRedisClient_LPush_Call{Call: _e.mock.On("LPush", ctx, key, value)}
}

func (_c *MockIRedisClient_LPush_Call) Run(run func(ctx context.Context, key string, value string)) *MockIRedisClient_LPush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRedisClient_LPush_Call) Return(err error) *MockIRedisClient_LPush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRedisClient_LPush_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockIRedisClient_LPush_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) Set(ctx context.Context, key string, val string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIRedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - ttl time.Duration
func (_e *MockIRedisClient_Expecter) Set(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockIRedisClient_Set_Call {
	return &MockIRedisClient_Set_Call{Call: _e.mock.On("Set", ctx, key, val, ttl)}
}

func (_c *MockIRedisClient_Set_Call) Run(run func(ctx context.Context, key string, val string, ttl time.Duration)) *MockIRedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRedisClient_Set_Call) Return(err error) *MockIRedisClient_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRedisClient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, val string, ttl time.Duration) error) *MockIRedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) SetNX(ctx context.Context, key string, val string, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, val, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, val, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRedisClient_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockIRedisClient_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val string
//   - ttl time.Duration
func (_e *MockIRedisClient_Expecter) SetNX(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockIRedisClient_SetNX_Call {
	return &MockIRedisClient_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, val, ttl)}
}

func (_c *MockIRedisClient_SetNX_Call) Run(run func(ctx context.Context, key string, val string, ttl time.Duration)) *MockIRedisClient_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRedisClient_SetNX_Call) Return(b bool, err error) *MockIRedisClient_SetNX_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIRedisClient_SetNX_Call) RunAndReturn(run func(ctx context.Context, key string, val string, ttl time.Duration) (bool, error)) *MockIRedisClient_SetNX_Call {
	_c.Call.Return(run)
	return _c
}

// ZAdd provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) ZAdd(ctx context.Context, key string, score float64, member string) error {
	ret := _mock.Called(ctx, key, score, member)

	if len(ret) == 0 {
		panic("no return value specified for ZAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, string) error); ok {
		r0 = returnFunc(ctx, key, score, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRedisClient_ZAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZAdd'
type MockIRedisClient_ZAdd_Call struct {
	*mock.Call
}

// ZAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - score float64
//   - member string
func (_e *MockIRedisClient_Expecter) ZAdd(ctx interface{}, key interface{}, score interface{}, member interface{}) *MockIRedisClient_ZAdd_Call {
	return &MockIRedisClient_ZAdd_Call{Call: _e.mock.On("ZAdd", ctx, key, score, member)}
}

func (_c *MockIRedisClient_ZAdd_Call) Run(run func(ctx context.Context, key string, score float64, member string)) *MockIRedisClient_ZAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRedisClient_ZAdd_Call) Return(err error) *MockIRedisClient_ZAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRedisClient_ZAdd_Call) RunAndReturn(run func(ctx context.Context, key string, score float64, member string) error) *MockIRedisClient_ZAdd_Call {
	_c.Call.Return(run)
	return _c
}
