// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIEmail creates a new instance of MockIEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEmail {
	mock := &MockIEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIEmail is an autogenerated mock type for the IEmail type
type MockIEmail struct {
	mock.Mock
}

type MockIEmail_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEmail) EXPECT() *MockIEmail_Expecter {
	return &MockIEmail_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MockIEmail
func (_mock *MockIEmail) SendEmail(to string, subject string, body string) error {
	ret := _mock.Called(to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIEmail_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockIEmail_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - to string
//   - subject string
//   - body string
func (_e *MockIEmail_Expecter) SendEmail(to interface{}, subject interface{}, body interface{}) *MockIEmail_SendEmail_Call {
	return &MockIEmail_SendEmail_Call{Call: _e.mock.On("SendEmail", to, subject, body)}
}

func (_c *MockIEmail_SendEmail_Call) Run(run func(to string, subject string, body string)) *MockIEmail_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIEmail_SendEmail_Call) Return(err error) *MockIEmail_SendEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIEmail_SendEmail_Call) RunAndReturn(run func(to string, subject string, body string) error) *MockIEmail_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}
