// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// CreateBucketWithCheck provides a mock function for the type MockIStorage
func (_mock *MockIStorage) CreateBucketWithCheck(ctx context.Context, bucketName string) error {
	ret := _mock.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucketWithCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucketName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStorage_CreateBucketWithCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucketWithCheck'
type MockIStorage_CreateBucketWithCheck_Call struct {
	*mock.Call
}

// CreateBucketWithCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
func (_e *MockIStorage_Expecter) CreateBucketWithCheck(ctx interface{}, bucketName interface{}) *MockIStorage_CreateBucketWithCheck_Call {
	return &MockIStorage_CreateBucketWithCheck_Call{Call: _e.mock.On("CreateBucketWithCheck", ctx, bucketName)}
}

func (_c *MockIStorage_CreateBucketWithCheck_Call) Run(run func(ctx context.Context, bucketName string)) *MockIStorage_CreateBucketWithCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIStorage_CreateBucketWithCheck_Call) Return(err error) *MockIStorage_CreateBucketWithCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStorage_CreateBucketWithCheck_Call) RunAndReturn(run func(ctx context.Context, bucketName string) error) *MockIStorage_CreateBucketWithCheck_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockIStorage
func (_mock *MockIStorage) PutObject(ctx context.Context, filepath string, bucketname string, objectName string, contentType string) error {
	ret := _mock.Called(ctx, filepath, bucketname, objectName, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, filepath, bucketname, objectName, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIStorage_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockIStorage_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - filepath string
//   - bucketname string
//   - objectName string
//   - contentType string
func (_e *MockIStorage_Expecter) PutObject(ctx interface{}, filepath interface{}, bucketname interface{}, objectName interface{}, contentType interface{}) *MockIStorage_PutObject_Call {
	return &MockIStorage_PutObject_Call{Call: _e.mock.On("PutObject", ctx, filepath, bucketname, objectName, contentType)}
}

func (_c *MockIStorage_PutObject_Call) Run(run func(ctx context.Context, filepath string, bucketname string, objectName string, contentType string)) *MockIStorage_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIStorage_PutObject_Call) Return(err error) *MockIStorage_PutObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIStorage_PutObject_Call) RunAndReturn(run func(ctx context.Context, filepath string, bucketname string, objectName string, contentType string) error) *MockIStorage_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
