// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scheduler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRedisClient creates a new instance of MockIRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRedisClient {
	mock := &MockIRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRedisClient is an autogenerated mock type for the IRedisClient type
type MockIRedisClient struct {
	mock.Mock
}

type MockIRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRedisClient) EXPECT() *MockIRedisClient_Expecter {
	return &MockIRedisClient_Expecter{mock: &_m.Mock}
}

// MoveScheduledToReady provides a mock function for the type MockIRedisClient
func (_mock *MockIRedisClient) MoveScheduledToReady(ctx context.Context, zsetKey string, readyListKey string, maxScore string) (int64, error) {
	ret := _mock.Called(ctx, zsetKey, readyListKey, maxScore)

	if len(ret) == 0 {
		panic("no return value specified for MoveScheduledToReady")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return returnFunc(ctx, zsetKey, readyListKey, maxScore)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = returnFunc(ctx, zsetKey, readyListKey, maxScore)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, zsetKey, readyListKey, maxScore)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRedisClient_MoveScheduledToReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveScheduledToReady'
type MockIRedisClient_MoveScheduledToReady_Call struct {
	*mock.Call
}

// MoveScheduledToReady is a helper method to define mock.On call
//   - ctx context.Context
//   - zsetKey string
//   - readyListKey string
//   - maxScore string
func (_e *MockIRedisClient_Expecter) MoveScheduledToReady(ctx interface{}, zsetKey interface{}, readyListKey interface{}, maxScore interface{}) *MockIRedisClient_MoveScheduledToReady_Call {
	return &MockIRedisClient_MoveScheduledToReady_Call{Call: _e.mock.On("MoveScheduledToReady", ctx, zsetKey, readyListKey, maxScore)}
}

func (_c *MockIRedisClient_MoveScheduledToReady_Call) Run(run func(ctx context.Context, zsetKey string, readyListKey string, maxScore string)) *MockIRedisClient_MoveScheduledToReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRedisClient_MoveScheduledToReady_Call) Return(n int64, err error) *MockIRedisClient_MoveScheduledToReady_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIRedisClient_MoveScheduledToReady_Call) RunAndReturn(run func(ctx context.Context, zsetKey string, readyListKey string, maxScore string) (int64, error)) *MockIRedisClient_MoveScheduledToReady_Call {
	_c.Call.Return(run)
	return _c
}
